BEGIN
EXECUTE IMMEDIATE 'DROP TABLE sync_event';
EXCEPTION
    WHEN OTHERS THEN IF SQLCODE != -00942 THEN RAISE; END IF;
END;
/

CREATE TABLE sync_event (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    table_name VARCHAR2(64) NOT NULL,
    op_type VARCHAR2(10) CHECK (op_type IN ('INSERT','UPDATE','DELETE')),
    pk_column_name VARCHAR2(64) NOT NULL,
    pk_value VARCHAR2(255) NOT NULL,
    status NUMBER DEFAULT 0,
    op_time DATE DEFAULT SYSDATE,
    source_db_type VARCHAR2(32) NOT NULL,
    error_msg VARCHAR2(1024),
    data_version NUMBER(10) NOT NULL
);
CREATE INDEX idx_sync_status ON sync_event(status);


-- [Oracle] users 版本维护 (BEFORE UPDATE)
CREATE OR REPLACE TRIGGER trg_users_ver
    BEFORE UPDATE ON users FOR EACH ROW
DECLARE
    v_user VARCHAR2(50);
BEGIN
    SELECT SYS_CONTEXT('USERENV', 'SESSION_USER') INTO v_user FROM DUAL;
    IF v_user != UPPER('dbsyncer') THEN
        :NEW.sync_version := :OLD.sync_version + 1;
    END IF;
END;
/

-- [Oracle] users 同步日志 (AFTER I/U/D)
CREATE OR REPLACE TRIGGER trg_users_sync
    AFTER INSERT OR UPDATE OR DELETE ON users FOR EACH ROW
DECLARE
    v_op   VARCHAR2(10);
    v_pk   VARCHAR2(255);
    v_ver  NUMBER;
    v_user VARCHAR2(50);
BEGIN
    SELECT SYS_CONTEXT('USERENV', 'SESSION_USER') INTO v_user FROM DUAL;
    IF v_user != UPPER('dbsyncer') THEN
        IF INSERTING THEN
            v_op  := 'INSERT'; v_pk  := TO_CHAR(:NEW.user_id); v_ver := :NEW.sync_version;
        ELSIF UPDATING THEN
            v_op  := 'UPDATE'; v_pk  := TO_CHAR(:NEW.user_id); v_ver := :NEW.sync_version;
        ELSIF DELETING THEN
            v_op  := 'DELETE'; v_pk  := TO_CHAR(:OLD.user_id); v_ver := :OLD.sync_version;
        END IF;
        INSERT INTO sync_event (table_name, op_type, pk_column_name, pk_value, status, op_time, source_db_type, data_version)
        VALUES ('users', v_op, 'user_id', v_pk, 0, SYSDATE, 'ORACLE', v_ver);
    END IF;
END;
/

-- [Oracle] students 版本维护 (BEFORE UPDATE)
CREATE OR REPLACE TRIGGER trg_students_ver
    BEFORE UPDATE ON students FOR EACH ROW
DECLARE
    v_user VARCHAR2(50);
BEGIN
    SELECT SYS_CONTEXT('USERENV', 'SESSION_USER') INTO v_user FROM DUAL;
    IF v_user != UPPER('dbsyncer') THEN
        :NEW.sync_version := :OLD.sync_version + 1;
    END IF;
END;
/

-- [Oracle] students 同步日志 (AFTER I/U/D)
CREATE OR REPLACE TRIGGER trg_students_sync
    AFTER INSERT OR UPDATE OR DELETE ON students FOR EACH ROW
DECLARE
    v_op VARCHAR2(10);
    v_pk VARCHAR2(255);
    v_ver NUMBER;
    v_user VARCHAR2(50);
BEGIN
    SELECT SYS_CONTEXT('USERENV', 'SESSION_USER') INTO v_user FROM DUAL;
    IF v_user != UPPER('dbsyncer') THEN
        IF INSERTING THEN
            v_op := 'INSERT'; v_pk := TO_CHAR(:NEW.student_id); v_ver := :NEW.sync_version;
        ELSIF UPDATING THEN
            v_op := 'UPDATE'; v_pk := TO_CHAR(:NEW.student_id); v_ver := :NEW.sync_version;
        ELSIF DELETING THEN
            v_op := 'DELETE'; v_pk := TO_CHAR(:OLD.student_id); v_ver := :OLD.sync_version;
        END IF;
        INSERT INTO sync_event (table_name, op_type, pk_column_name, pk_value, status, op_time, source_db_type, data_version)
        VALUES ('students', v_op, 'student_id', v_pk, 0, SYSDATE, 'ORACLE', v_ver);
    END IF;
END;
/

-- [Oracle] courses 版本维护 (BEFORE UPDATE)
CREATE OR REPLACE TRIGGER trg_courses_ver
    BEFORE UPDATE ON courses FOR EACH ROW
DECLARE
    v_user VARCHAR2(50);
BEGIN
    SELECT SYS_CONTEXT('USERENV', 'SESSION_USER') INTO v_user FROM DUAL;
    IF v_user != UPPER('dbsyncer') THEN
        :NEW.sync_version := :OLD.sync_version + 1;
    END IF;
END;
/

-- [Oracle] courses 同步日志 (AFTER I/U/D)
CREATE OR REPLACE TRIGGER trg_courses_sync
    AFTER INSERT OR UPDATE OR DELETE ON courses FOR EACH ROW
DECLARE
    v_op VARCHAR2(10);
    v_pk VARCHAR2(255);
    v_ver NUMBER;
    v_user VARCHAR2(50);
BEGIN
    SELECT SYS_CONTEXT('USERENV', 'SESSION_USER') INTO v_user FROM DUAL;
    IF v_user != UPPER('dbsyncer') THEN
        IF INSERTING THEN
            v_op := 'INSERT'; v_pk := TO_CHAR(:NEW.course_id); v_ver := :NEW.sync_version;
        ELSIF UPDATING THEN
            v_op := 'UPDATE'; v_pk := TO_CHAR(:NEW.course_id); v_ver := :NEW.sync_version;
        ELSIF DELETING THEN
            v_op := 'DELETE'; v_pk := TO_CHAR(:OLD.course_id); v_ver := :OLD.sync_version;
        END IF;
        INSERT INTO sync_event (table_name, op_type, pk_column_name, pk_value, status, op_time, source_db_type, data_version)
        VALUES ('courses', v_op, 'course_id', v_pk, 0, SYSDATE, 'ORACLE', v_ver);
    END IF;
END;
/

-- [Oracle] enrollments 版本维护 (BEFORE UPDATE)
CREATE OR REPLACE TRIGGER trg_enrollments_ver
    BEFORE UPDATE ON enrollments FOR EACH ROW
DECLARE
    v_user VARCHAR2(50);
BEGIN
    SELECT SYS_CONTEXT('USERENV', 'SESSION_USER') INTO v_user FROM DUAL;
    IF v_user != UPPER('dbsyncer') THEN
        :NEW.sync_version := :OLD.sync_version + 1;
    END IF;
END;
/

-- [Oracle] enrollments 同步日志 (AFTER I/U/D)
CREATE OR REPLACE TRIGGER trg_enrollments_sync
    AFTER INSERT OR UPDATE OR DELETE ON enrollments FOR EACH ROW
DECLARE
    v_op VARCHAR2(10);
    v_pk VARCHAR2(255);
    v_ver NUMBER;
    v_user VARCHAR2(50);
BEGIN
    SELECT SYS_CONTEXT('USERENV', 'SESSION_USER') INTO v_user FROM DUAL;
    IF v_user != UPPER('dbsyncer') THEN
        IF INSERTING THEN
            v_op := 'INSERT'; v_pk := TO_CHAR(:NEW.enrollment_id); v_ver := :NEW.sync_version;
        ELSIF UPDATING THEN
            v_op := 'UPDATE'; v_pk := TO_CHAR(:NEW.enrollment_id); v_ver := :NEW.sync_version;
        ELSIF DELETING THEN
            v_op := 'DELETE'; v_pk := TO_CHAR(:OLD.enrollment_id); v_ver := :OLD.sync_version;
        END IF;
        INSERT INTO sync_event (table_name, op_type, pk_column_name, pk_value, status, op_time, source_db_type, data_version)
        VALUES ('enrollments', v_op, 'enrollment_id', v_pk, 0, SYSDATE, 'ORACLE', v_ver);
    END IF;
END;
/

-- [Oracle] books 版本维护 (BEFORE UPDATE)
CREATE OR REPLACE TRIGGER trg_books_ver
    BEFORE UPDATE ON books FOR EACH ROW
DECLARE
    v_user VARCHAR2(50);
BEGIN
    SELECT SYS_CONTEXT('USERENV', 'SESSION_USER') INTO v_user FROM DUAL;
    IF v_user != UPPER('dbsyncer') THEN
        :NEW.sync_version := :OLD.sync_version + 1;
    END IF;
END;
/

-- [Oracle] books 同步日志 (AFTER I/U/D)
CREATE OR REPLACE TRIGGER trg_books_sync
    AFTER INSERT OR UPDATE OR DELETE ON books FOR EACH ROW
DECLARE
    v_op VARCHAR2(10);
    v_pk VARCHAR2(255);
    v_ver NUMBER;
    v_user VARCHAR2(50);
BEGIN
    SELECT SYS_CONTEXT('USERENV', 'SESSION_USER') INTO v_user FROM DUAL;
    IF v_user != UPPER('dbsyncer') THEN
        IF INSERTING THEN
            v_op := 'INSERT'; v_pk := TO_CHAR(:NEW.book_id); v_ver := :NEW.sync_version;
        ELSIF UPDATING THEN
            v_op := 'UPDATE'; v_pk := TO_CHAR(:NEW.book_id); v_ver := :NEW.sync_version;
        ELSIF DELETING THEN
            v_op := 'DELETE'; v_pk := TO_CHAR(:OLD.book_id); v_ver := :OLD.sync_version;
        END IF;
        INSERT INTO sync_event (table_name, op_type, pk_column_name, pk_value, status, op_time, source_db_type, data_version)
        VALUES ('books', v_op, 'book_id', v_pk, 0, SYSDATE, 'ORACLE', v_ver);
    END IF;
END;
/

-- [Oracle] borrow_records 版本维护 (BEFORE UPDATE)
CREATE OR REPLACE TRIGGER trg_borrow_records_ver
    BEFORE UPDATE ON borrow_records FOR EACH ROW
DECLARE
    v_user VARCHAR2(50);
BEGIN
    SELECT SYS_CONTEXT('USERENV', 'SESSION_USER') INTO v_user FROM DUAL;
    IF v_user != UPPER('dbsyncer') THEN
        :NEW.sync_version := :OLD.sync_version + 1;
    END IF;
END;
/

-- [Oracle] borrow_records 同步日志 (AFTER I/U/D)
CREATE OR REPLACE TRIGGER trg_borrow_records_sync
    AFTER INSERT OR UPDATE OR DELETE ON borrow_records FOR EACH ROW
DECLARE
    v_op VARCHAR2(10);
    v_pk VARCHAR2(255);
    v_ver NUMBER;
    v_user VARCHAR2(50);
BEGIN
    SELECT SYS_CONTEXT('USERENV', 'SESSION_USER') INTO v_user FROM DUAL;
    IF v_user != UPPER('dbsyncer') THEN
        IF INSERTING THEN
            v_op := 'INSERT'; v_pk := TO_CHAR(:NEW.record_id); v_ver := :NEW.sync_version;
        ELSIF UPDATING THEN
            v_op := 'UPDATE'; v_pk := TO_CHAR(:NEW.record_id); v_ver := :NEW.sync_version;
        ELSIF DELETING THEN
            v_op := 'DELETE'; v_pk := TO_CHAR(:OLD.record_id); v_ver := :OLD.sync_version;
        END IF;
        INSERT INTO sync_event (table_name, op_type, pk_column_name, pk_value, status, op_time, source_db_type, data_version)
        VALUES ('borrow_records', v_op, 'record_id', v_pk, 0, SYSDATE, 'ORACLE', v_ver);
    END IF;
END;
/

-- [Oracle] shop_items 版本维护 (BEFORE UPDATE)
CREATE OR REPLACE TRIGGER trg_shop_items_ver
    BEFORE UPDATE ON shop_items FOR EACH ROW
DECLARE
    v_user VARCHAR2(50);
BEGIN
    SELECT SYS_CONTEXT('USERENV', 'SESSION_USER') INTO v_user FROM DUAL;
    IF v_user != UPPER('dbsyncer') THEN
        :NEW.sync_version := :OLD.sync_version + 1;
    END IF;
END;
/

-- [Oracle] shop_items 同步日志 (AFTER I/U/D)
CREATE OR REPLACE TRIGGER trg_shop_items_sync
    AFTER INSERT OR UPDATE OR DELETE ON shop_items FOR EACH ROW
DECLARE
    v_op VARCHAR2(10);
    v_pk VARCHAR2(255);
    v_ver NUMBER;
    v_user VARCHAR2(50);
BEGIN
    SELECT SYS_CONTEXT('USERENV', 'SESSION_USER') INTO v_user FROM DUAL;
    IF v_user != UPPER('dbsyncer') THEN
        IF INSERTING THEN
            v_op := 'INSERT'; v_pk := TO_CHAR(:NEW.item_id); v_ver := :NEW.sync_version;
        ELSIF UPDATING THEN
            v_op := 'UPDATE'; v_pk := TO_CHAR(:NEW.item_id); v_ver := :NEW.sync_version;
        ELSIF DELETING THEN
            v_op := 'DELETE'; v_pk := TO_CHAR(:OLD.item_id); v_ver := :OLD.sync_version;
        END IF;
        INSERT INTO sync_event (table_name, op_type, pk_column_name, pk_value, status, op_time, source_db_type, data_version)
        VALUES ('shop_items', v_op, 'item_id', v_pk, 0, SYSDATE, 'ORACLE', v_ver);
    END IF;
END;
/

-- [Oracle] orders 版本维护 (BEFORE UPDATE)
CREATE OR REPLACE TRIGGER trg_orders_ver
    BEFORE UPDATE ON orders FOR EACH ROW
DECLARE
    v_user VARCHAR2(50);
BEGIN
    SELECT SYS_CONTEXT('USERENV', 'SESSION_USER') INTO v_user FROM DUAL;
    IF v_user != UPPER('dbsyncer') THEN
        :NEW.sync_version := :OLD.sync_version + 1;
    END IF;
END;
/

-- [Oracle] orders 同步日志 (AFTER I/U/D)
CREATE OR REPLACE TRIGGER trg_orders_sync
    AFTER INSERT OR UPDATE OR DELETE ON orders FOR EACH ROW
DECLARE
    v_op VARCHAR2(10);
    v_pk VARCHAR2(255);
    v_ver NUMBER;
    v_user VARCHAR2(50);
BEGIN
    SELECT SYS_CONTEXT('USERENV', 'SESSION_USER') INTO v_user FROM DUAL;
    IF v_user != UPPER('dbsyncer') THEN
        IF INSERTING THEN
            v_op := 'INSERT'; v_pk := TO_CHAR(:NEW.order_id); v_ver := :NEW.sync_version;
        ELSIF UPDATING THEN
            v_op := 'UPDATE'; v_pk := TO_CHAR(:NEW.order_id); v_ver := :NEW.sync_version;
        ELSIF DELETING THEN
            v_op := 'DELETE'; v_pk := TO_CHAR(:OLD.order_id); v_ver := :OLD.sync_version;
        END IF;
        INSERT INTO sync_event (table_name, op_type, pk_column_name, pk_value, status, op_time, source_db_type, data_version)
        VALUES ('orders', v_op, 'order_id', v_pk, 0, SYSDATE, 'ORACLE', v_ver);
    END IF;
END;
/